# -*- coding: utf-8 -*-
"""halo_dunia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WvLUNIjcQM_fYSN3ABE6FStx0pfHz3R0
"""

print('Halo Dunia!')
print ('Belajar AI !')
print('Yes !')